version: "3.8"

services:
  eazyrooms_users_service:
    image: eazyrooms/eazyrooms_users_service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
    networks:
      - eazyrooms-network

networks:
  eazyrooms-network:
    driver: overlay
